# Generated by Django 2.2.17 on 2020-12-28 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customtext_jhbjhgjhg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='jhbjhgjhg',
        ),
    ]
